### ISSUE TITLE
Discussion: Use build.zig as build system

### ISSUE THREAD

**Issue by ostcar** [lukewilliamboswell/roc-platform-template-go#6]
In the [roc-aoc-platform](https://github.com/ostcar/roc-aoc-platform) I used a `build.zig` to build the platform. I would say, that the zig build-system has a learning curve, but is superior to the `build.roc`. Specially the zig build cache is wonderful.

Would it be ok for you, if I replace the build.roc with a build.zig file? There are good arguments for `build.roc`. The `build.roc` file is similar in all your platform-templates. So it might be easier for newcomers. This is not a zig platform, but a go platform. So it might be strange to see this zig file. But on the other hand, zig is needed anyway for cross compilation.

**Comment by lukewilliamboswell** [comment]
I think I would prefer a roc script for now. 

I'm not opposed to zig for this, but it may not be familiar to go programmers who are interested in this platform.
